# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-site:
    docker:
      - image: circleci/node:8.10 
    steps:
      - checkout
           # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run deploy
      - add_ssh_keys:
          fingerprints:
            - "d4:ab:d2:a3:ed:58:6c:33:0b:15:6b:46:19:22:2a:28"
      - run:
          name: Deploy docs to gh-pages branch
          command: | 
            git config --global user.email "ci-build@dionnephua.com"
            git config --global user.name "ci-build"
            CI=false yarn deploy
          
workflows:
  version: 2
  build:
    jobs:
      - build-site:
          filters:
            branches:
              only: master
        
